### PR TITLE
Add actions for mesh pieces to ElmerGUI Simulation section.

### PR DESCRIPTION
**Pull request by richb2k**
New ElmerGUI check box for 'Calculate Mesh Pieces', and new ElmerGUI text box to enter the number of 'Desired Mesh Pieces'.  
By default, if the check box is unchecked and the text box is empty, then nothing is added to the Simulation section of the sif file.  Checking the check box will add 'Calculate Mesh Pieces = Logical True'.  Likewise, if a number is entered into the text box, such as a '1', then 'Desired Mesh Pieces = Integer 1' will be added to the Simulation section.  If both the check box is checked and a number is added to the text box, then both statements will be added to the sif file.

### CODE REVIEW

**Comment by raback** [comment]
Nice work! I would just recommend adding the keywords "Calculate Mesh Pieces" and "Desired Mesh Pieces" to fem/src/SOLVER.KEYWORDS so that the type (Logical/Integer) does not need to be given. I know not all keywords are there but if they make the GUI they also earn the place in the SOLVER.KEYWORDS.

**Comment by richb2k** [comment]
Okay, I'll work on adding both of those keywords.  I tried the other day, but without success, so it may take me a day or two to figure out what went wrong.

**Comment by raback** [comment]
Adding the keyword unfortunately does not seem to update itself with "make install" or alike. For some reason you need a clean build. Or you can cheat by copying it manually. It is copied as is in style:
elmeruser@elmeruser-VirtualBox:~/elmerfem/fem/src$ cp SOLVER.KEYWORDS  /opt/elmer/share/elmersolver/lib/SOLVER.KEYWORDS

**Comment by richb2k** [comment]
Working in Windows 10, I edited the solver.keywords file directly in C:\Program Files\Elmer 9.0-Release\share\elmersolver\lib, and the two added keywords are still not being recognized. 
ERROR:: LoadInputFile:  Unknown specifier: [true]
ERROR:: LoadInputFile:  In section: [simulation]
ERROR:: LoadInputFile:  For property name:[calculate mesh pieces]
I'll add the keywords in a separate branch, then if accepted, I'll wait for a windows binary build to try ElmerGUI again.

**Comment by richb2k** [comment]
While looking for something else, I ran the test 'radiation2', and it failed with the same type of keyword error:
ERROR:: LoadInputFile:  Unknown specifier: [1.0e-10]
ERROR:: LoadInputFile:  In section: [solver 1]
ERROR:: LoadInputFile:  For property name:[minimum gebhart factor]
Do any other tests fail with this type of keyword error?

**Comment by richb2k** [comment]
Update sif generator, removing Logical and Integer types from the sif commands.

**Pull request merged**
