### PR TITLE
Build ElmerIce and run tests in CI on Windows

### PR DESCRIPTION
**Pull request by mmuetzel**
IIUC, the libraries built by ElmerIce are used as modules for the ElmerSolver library. Link them in the same directory as the other ElmerSolver modules.

This allows to run more ctests of ElmerIce in the build tree on Windows. It also makes the file layout during the ctests more similar to the layout after installation.

### CODE REVIEW

**Comment by mmuetzel** [comment]
Without these changes some tests fail with errors like the following:
```
Can not find ElmerIceUSF.
Can not find ElmerIceUSF.dll.
Can not find .\ElmerIceUSF.
Can not find .\ElmerIceUSF.dll.
Can not find D:/repo/elmerfem/.build/fem/src/modules\ElmerIceUSF.
Can not find D:/repo/elmerfem/.build/fem/src/modules\ElmerIceUSF.dll.
Can not find D:/repo/elmerfem/.build/elmerice/Solvers:D:/repo/elmerfem/.build/elmerice/Solvers/GridDataReader:D:/repo/elmerfem/.build/elmerice/Solvers/ScatteredDataInterpolator:D:/repo/elmerfem/.build/elmerice/Solvers/MeshAdaptation_2D:D:/repo/elmerfem/.build/elmerice/UserFunctions\ElmerIceUSF.
Can not find D:/repo/elmerfem/.build/elmerice/Solvers:D:/repo/elmerfem/.build/elmerice/Solvers/GridDataReader:D:/repo/elmerfem/.build/elmerice/Solvers/ScatteredDataInterpolator:D:/repo/elmerfem/.build/elmerice/Solvers/MeshAdaptation_2D:D:/repo/elmerfem/.build/elmerice/UserFunctions\ElmerIceUSF.dll.
```

**Comment by mmuetzel** [comment]
I'd like to rebase this on top of #522 (if that PR can be accepted).
Marked as a draft for now.

**Comment by mmuetzel** [comment]
All ElmerIce tests that are run in CI are passing with these changes.

**Comment by mmuetzel** [comment]
Are the proposed changes ok to be merged?

There is CI now that checks building ElmerIce and running some of its tests in CI on Ubuntu. The changes from this PR don't break Ubuntu and they fix running the tests on Windows (and they add tests for it in CI).
Apparently, these changes also address similar(?) issues on macOS.

**Comment by mmuetzel** [comment]
This PR conflicts with #576. I'll try to rebase this after that PR is merged (if that PR is acceptable).

Marking as draft for now.

**Comment by raback** [comment]
Just accepted #576

**Comment by mmuetzel** [comment]
Thanks. Rebased now.

**Pull request merged**
