### PR TITLE
Update CMakeLists for Mac

### PR DESCRIPTION
**Pull request by ShamoX**
This is a try to integrate/solve #313.

For now, it compiles, but I cannot see on my MacBook Pro M2 the 3D Mesh of the first example of the tutorial (3D Heat: samples/step/pump_carter_sup.stp).

Help welcome. I have not many errors:

```
(base) rlaures@Liant-Ordi-alpha ~ % ElmerGUI                  
Load /usr/local/bin/../share/ElmerGUI/edf/egini.xml... done
Load tetgen plugin... not found
Tetgen functionality unavailable
Constructing ElmergridAPI... done
QObject::connect: No such signal MeshingThread::terminated() in /Users/rlaures/dev/liant/elmerfem/ElmerGUI/Application/src/mainwindow.cpp:215
Load /usr/local/bin/../share/ElmerGUI/edf/edf.xml... done
Load /usr/local/bin/../share/ElmerGUI/edf/navier-stokes.xml... done
Load /usr/local/bin/../share/ElmerGUI/edf/meshdeform.xml... done
Load /usr/local/bin/../share/ElmerGUI/edf/helmholtz.xml... done
Load /usr/local/bin/../share/ElmerGUI/edf/heatequation.xml... done
Load /usr/local/bin/../share/ElmerGUI/edf/electrostatics.xml... done
Load /usr/local/bin/../share/ElmerGUI/edf/linearelasticity.xml... done
Load /usr/local/bin/../share/ElmerGUI/edf/resultoutput.xml... done
QObject::connect: No such signal MeshingThread::terminated() in /Users/rlaures/dev/liant/elmerfem/ElmerGUI/Application/src/objectbrowser.cpp:185
Initialize GL
Vendor: Apple
Renderer: Apple M2
Version: 2.1 Metal - 83.1
2023-04-12 03:36:52.263 ElmerGUI[48837:2642655] +[CATransaction synchronize] called within transaction
2023-04-12 03:36:52.336 ElmerGUI[48837:2642655] +[CATransaction synchronize] called within transaction
Loading from directory /Users/rlaures/dev/liant/ElmerExamples/Heat equation - 3D
Loading elmer mesh files
Summary:
Nodes: 0
Point elements: 0
Edge elements: 0
Surface elements: 0
Volume elements: 0
Found 0 edges on boundary
Creating edge indexes 
0 boundary edges were numbered up to index 0
Ready
2023-04-12 03:37:11.175 ElmerGUI[48837:2642655] +[CATransaction synchronize] called within transaction
2023-04-12 03:37:11.214 ElmerGUI[48837:2642655] +[CATransaction synchronize] called within transaction
Unable to open file: file type unknown
Unable to (re)mesh: no input data or mesh generator (please make sure that your input file suffix is in lower case)
2023-04-12 03:37:49.710 ElmerGUI[48837:2642655] +[CATransaction synchronize] called within transaction
2023-04-12 03:37:49.753 ElmerGUI[48837:2642655] +[CATransaction synchronize] called within transaction
2023-04-12 03:37:50.446 ElmerGUI[48837:2642655] +[CATransaction synchronize] called within transaction
2023-04-12 03:37:54.447 ElmerGUI[48837:2642655] +[CATransaction synchronize] called within transaction
Output directory /Users/rlaures/dev/liant/ElmerExamples/Heat equation - 3D
Saving elmer mesh files
Saving 0 nodes
Saving 0 elements
Saving 0 boundary elements
Ready
(base) rlaures@Liant-Ordi-alpha ~ % 
```

The relevant error seems to me to be:

```
Unable to open file: file type unknown
Unable to (re)mesh: no input data or mesh generator (please make sure that your input file suffix is in lower case)
```

### CODE REVIEW

**Comment by raback** [comment]
Thanx. I will merge when you ask. If there are additional fixes just make a new PR. Unfortunately the developer team is not using mac at all so our hope is on the community.

**Comment by AkthemRehab** [comment]
Hello, I am having an M2 mac too. While I succeeded in installing Elmer following the steps in this video: https://www.youtube.com/watch?v=rQhSYKHw3HM and the workaround from #313.

I am failing though to follow through with the GUI and MPI installation as per https://www.youtube.com/watch?v=h7PswPM9qtk and my comment in #313 .

Could you please tell me if you made it work and kindly share how if yes?

**Comment by luzpaz** [comment]
Any progress on this?

**Comment by raback** [comment]
Is this any more relevant as there has been a lot happening around cmake lately?

**Comment by mmuetzel** [comment]
I don't think the changes from this PR are relevant any longer. Elmer is building in CI on macOS using packages from Homebrew without the proposed changes.

**Comment by raback** [comment]
Thanx Markus! I will then proceed to close this.

**Pull request closed without merging**
