### PR TITLE
Elmerice

### PR DESCRIPTION
**Pull request by jbrondex**
Hi, 

I propose substantial modifications to the ComputeDevStressNS solver so that it becomes compatible with the snow/firn (i.e. Porous Solver) rheology. It was already possible to get deviatoric stresses directly from the Porous Solver but in that case their nodal values were computed as the average of all values evaluated within elements sharing the considered node. This led to issues at partition interfaces. It is therefore cleaner to use the variational method as done in the ComputeDevStressNS solver for the Stokes case.
 
This adaptation has several implications:
- To avoid code duplication for what regards computation of effective stress and compressibility parameter which are now needed in both the Porous and the new ComputeDevStress solver, I have created the module Utils/PorousMaterialModels.F90 that is called by both solvers.

- Naturally, I have modified the Porous solver so that operations related to computation of effective viscosity and compressibility are not hard-coded anymore but done via the new PorousMaterialModels module

- The functions a and b which are needed for the firn rheology are now included in the PorousMaterialModels module. Therefore, I have deleted the Solver/fAandfB_in.F90 file.

- I have slightly modified these two functions: for the full-ice case (i.e. relative density = 1) we must have a = 1 and b = 0. I have changed the if test to apply these two limit values from If D >= 1.0_dp to if D > 0.99_dp. This proves necessary to avoid outlier values in nodal stress, with very little change on obtained velocity field. 

- To make it clear that the ComputeDevStress solver is no longer exclusively compatible with the Stokes solver, I have changed its name from ComputeDevStressNS.F90 to ComputeDevStress.F90

- I have modified the Solver/CMakeLists.txt accordingly

- I have added the PorousMaterialModels module to the Utils/CMakeLists.txt

- I have updated the documentation of the Porous and ComputeDevStress Solver

Of course, I have checked on my current working case that the velocity and stress solutions are preserved.

Cheers,

Julien

### CODE REVIEW

**Comment by tzwinger** [comment]
I tried to manually merge and configure and get an error: You seem to have removed `elmerice/Solvers/fAandfB._in.F90`, but in the merged version `elmerice/Solvers/CMakeLists.txt` still demands it - not sure what to exactly do about this

**Comment by jbrondex** [comment]
> I tried to manually merge and configure and get an error: You seem to have removed `elmerice/Solvers/fAandfB._in.F90`, but in the merged version `elmerice/Solvers/CMakeLists.txt` - not sure what to exactly do about this

Hi Thomas, 
Yes I forgot removing fAandfB_in.F90 from the elmerice/Solvers/CMakeLists.txt. It should indeed be removed as the functions are now included in the PorousMaterialModels module. 
I haven't retried yet the full compilation of elmer after the changes I made. I have only compiled the 3 files I changed  (i.e. Porous Solver, ComputeDevStress solver and PorousMaterialModels module) locally. So there may have been omissions in the updated compilation files such as the one you pinpointed. I'll check that next week. 
Cheers,

**Comment by jbrondex** [comment]
Hi, 
I have recompiled Elmer this morning, it seems that now everything is working fine.

Cheers,

Julien

**Comment by tzwinger** [comment]
These are the Elmer/Ice related tests that fail on my side after merging with elmerice:
`	  4 - Calving3D (Failed)
	  5 - Calving3D_lset (Failed)
	  8 - DGsolver (Failed)
	  9 - Damage (Failed)
	 21 - FrictionHeatMasked (Failed)
	 25 - Friction_Weertman2 (Failed)
	 26 - Friction_WeertmanNewton (Failed)
	 27 - Friction_WeertmanNewton2 (Failed)
	 29 - GL_MISMIP (Failed)
	 39 - Hydro_Coupled (Failed)
	 40 - Hydro_SedOnly (Failed)
	 43 - InvMeth_AdjRobin (Failed)
	 45 - MISMIP_FS-SSA (Failed)
	 49 - MMG2D_Transient (Failed)
	 50 - Permafrost_Biot (Failed)
	 58 - ScatteredDataInterpolator (Failed)
	 69 - XIOS (Failed)
	 70 - XIOS2 (Failed)
`
Most worrying:  `DGsolver` converges now to a different norm

**Comment by fgillet** [comment]
Thanks Thomas;
Here is the list of elmerice failed tests from my side after merging julien's PR:
          4 - Calving3D (Failed)
	  7 - DGsolver (Failed)
	  8 - Damage (Failed)
	 20 - FrictionHeatMasked (Failed)
	 21 - Friction_Coulomb (Failed)
	 23 - Friction_Weertman (Failed)
	 28 - GL_MISMIP (Failed)
	 37 - Hydro_Coupled (Failed)
	 38 - Hydro_SedOnly (Failed)
	 41 - InvMeth_AdjRobin (Failed)
	 43 - MISMIP_FS-SSA (Failed)
	 47 - MMG2D_Transient (Failed)
	 48 - Permafrost_Biot (Failed)

- Norm in DGsolver changed after this modification:

`_- have slightly modified these two functions: for the full-ice case (i.e. relative density = 1) we must have a = 1 and b = 0. I have changed the if test to apply these two limit values from If D >= 1.0_dp to if D > 0.99_dp. This proves necessary to avoid outlier values in nodal stress, with very little change on obtained velocity field_`
@jbrondex please revise the test or code;

- Test Damage use ComputeDevStress, but gives consistent norm after and before the code modification; this will have to be revised

- At first look the other failed tests are independant of Julien's code changes and will have to be checked more carrefully.

**Comment by jbrondex** [comment]
After several checks and as Fabien said:
- The Damage solver test was already failing before my modifications and the obtained norm after my modification is the same as the one obtained before.
- The DGsolver test is indeed failing due to my modifications. As Fabien said, it is due to the modification on the condition to apply pure ice values to functions a and b of the porous rheology (i.e. a=1 and b =0, respectively). The original test to apply pure ice condition was: "if D>=1.0_dp". This was giving outlier values of stress at some nodes. I can explain more the problem if needed, but in a few words, this is due to the calculation of the invariant of the strain-rate tensor. To avoid this problem I have changed the test to: "if D>0.99_dp". If I switch back this condition to the original one, the  DGsolver test passes. I made some sensitivity evaluation, the  DGsolver test fails with condition "if D>0.999" and passes with condition "if D>0.9999".  For now, I propose to keep the condition "if D>0.99_dp" and to change the reference norm of the DGsolver test so that it passes with this condition. This is the purpose of my last commit.  I have also updated the documentation of the Porous Solver accordingly. Of course, I would welcome further discussions/comments on this point.

**Pull request merged**
