### PR TITLE
Fix misc. typos in fem/src

### PR DESCRIPTION
**Pull request by luzpaz**
Found via `codespell -q 3 -I ../elmerfem-word-whitelist.txt -S ./mathlibs,./contrib,./misc` whereby the whitelist consists of:
```
addres
amin
ang
ba
cna
dum
iff
impres
indeces
infor
ith
muder
nd
objext
ot
pres
strat
te
teh
tim
uint
```

### CODE REVIEW

**Comment by juharu** [comment]
Thanks again!

 One test ("ContactPatch3DNamesAndAutonum3") uses a misspelled keyword ("mass consistant normals") and fails now when the spelling was corrected in SOLVER.KEYWORDS -file. The test might also miss the norm tolerance after corrected as the actual code seemed to have the correct spelling and so the feature was not really activated before.

Also, these (there are several of these in your patch) don't look right on my display after the changes:  

! *  Authors: Esko Järvinen, Mikko Lyly, Peter Råback
! *  Authors: Esko J�rvinen, Mikko Lyly, Peter R�back

but fine before...

BR, Juha

**Comment by luzpaz** [comment]
FYI, any change to SOLVER.KEYWORDS was reverted in a0af9e7

As for the Authors, I don't see the issue in this patch. Perhaps you are referring to a previous patch? https://github.com/ElmerCSC/elmerfem/pull/173

**Comment by juharu** [comment]
Thanks.
>As for the Authors, I don't see the issue in this patch. Perhaps you are referring to a previous patch? #173
No, that patch had none? This patch has several. What I see in my display is that the letters "å" & "ä" are
both replaced by a black diamond shape with white question mark inside...

**Comment by luzpaz** [comment]
Actually, I'm confused now. I can see from the raw text diff (https://patch-diff.githubusercontent.com/raw/ElmerCSC/elmerfem/pull/174.patch) that that line has been altered but in my git gui i do not see that modification... :confused:

image

**Comment by juharu** [comment]
Yes well, me too! Applied your patch to a "devel" copy and did "git diff" afterwards, didn't show any changes in "Authors" stuff. I guess it's oukei. I'll do the merge...

**Comment by juharu** [comment]
Hi 

I did the merge, but now there are seemingly some problems with how the letters look in my display. 

Doing 

> file *.F90 

in fem/src/modules gives (for example). 

... 

MagneticSolve.F90: ASCII text 
MagnetoDynamics2D.F90: UTF-8 Unicode text 
Mesh2MeshSolver.F90: UTF-8 Unicode text 
MeshSolve.F90: ASCII text 
ModelPDE.F90: ASCII text 
MovingElstatSolver.F90: UTF-8 Unicode text 
NonphysicalMeshSolve.F90: UTF-8 Unicode text 
NormalSolver.F90: UTF-8 Unicode text 
OdeSolver.F90: UTF-8 Unicode text 
OpenFoam2ElmerIO.F90: ISO-8859 text 
ParStokes.F90: ASCII text 
ParticleAdvector.F90: ISO-8859 text 
.. 

The file "type" is probably the reason, i think. Don't really know what to do about it, 
if anything, though. Anyone ? 



BR, Juha

**Pull request merged**
