### PR TITLE
Minor update to matc.  Allows 'exit' or 'quit' to work as expected when running from the command line.

### PR DESCRIPTION
**Pull request by richb2k**
Compiled and tested on Windows 10 and on Ubuntu 20 in the Elmer VM.

### CODE REVIEW

**Comment by richb2k** [comment]
This update is a change to the executable version of matc, that can be called from the command line.  This change will not effect calls to mtc_domath().

**Comment by juharu** [comment]
Merged now, thanks Rich!

**Comment by richb2k** [comment]
You are welcome.  I have a question about matc and elmergrid.  I see there is an option to compile elmergrid with matc, and in fact it works.  Is there a historical reason to not compile elmergrid with matc for production?
Rich.

**Comment by raback** [comment]
There is really no reason not to compile ElmerGrid with MATC. Could be useful for some users.

**Comment by richb2k** [comment]
I guess the hardest part would be to change cmake to build them together.

**Comment by richb2k** [comment]
So, I used building of matc with a shared library as a model, as it is currently implemented.  I made some changes to cmake, and now elmergrid will build with matc activated.  As a side product, libelmergrid.dll is created.  Rather than adding a PR for something experimental, take a look at this github repo that has the changes:  [https://github.com/richb2k/elmerfem](url)  If someone could check that building and packaging of elmerfem works properly, then I'd be happy to add a PR.  Thanks,  Rich.
Edit:  the changes compile and are working in Windows 10.  Elmergrid can process matc statements with the change in cmake.  Not sure how the changes will work with packaging, such as storing the dll properly in bin.

**Pull request merged**
