### PR TITLE
Avoid using MPI_IN_PLACE if it isn't supported.

### LINKED ISSUE #521: Test `CurvedBoundaryCylHquadratic` failing on Windows (MinGW)
The test `CurvedBoundaryCylHquadratic` is currently failing on Windows with the following output:
```
$ ../../src/ElmerSolver
ELMER SOLVER (v 9.0) STARTED AT: 2024/08/09 17:52:14
ParCommInit:  Initialize #PEs:            1
MAIN:
MAIN: =============================================================
MAIN: ElmerSolver finite element software, Welcome!
MAIN: This program is free software licensed under (L)GPL
MAIN: Copyright 1st April 1995 - , CSC - IT Center for Science Ltd.
MAIN: Webpage http://www.csc.fi/elmer, Email elmeradm@csc.fi
MAIN: Version: 9.0 (Rev: 733f7f2af, Compiled: 2024-08-09)
MAIN:  Running one task without MPI parallelization.
MAIN:  Running with just one thread per task.
MAIN:  Zoltan library linked in.
MAIN: =============================================================
MAIN:
MAIN:
MAIN: -------------------------------------
MAIN: Reading Model: case.sif
LoadInputFile: Scanning input file: case.sif
LoadInputFile: Scanning only size info
LoadInputFile: First time visiting
LoadInputFile: Reading base load of sif file
LoadInputFile: Loading input file: case.sif
LoadInputFile: Reading base load of sif file
CheckKeyword:  Unlisted keyword: [vtu: constraint modes analysis] in section: [simulation]
CheckKeyword:  Unlisted keyword: [increase element order] in section: [simulation]
CheckKeyword:  Unlisted keyword: [constraint modes matrix results] in section: [solver 1]
CheckKeyword:  Unlisted keyword: [expression 1] in section: [solver 2]
CheckKeyword:  Unlisted keyword: [expression 2] in section: [solver 2]
CheckKeyword:  Unlisted keyword: [follow cylinder boundary] in section: [boundary condition 1]
CheckKeyword:  Unlisted keyword: [follow cylinder boundary] in section: [boundary condition 2]
LoadInputFile: Number of BCs: 4
LoadInputFile: Number of Body Forces: 0
LoadInputFile: Number of Initial Conditions: 0
LoadInputFile: Number of Materials: 1
LoadInputFile: Number of Equations: 1
LoadInputFile: Number of Solvers: 2
LoadInputFile: Number of Bodies: 2
ListTagKeywords: Setting weight for keywords!
ListTagKeywords: No parameters width suffix: normalize by area
ListTagKeywords: Setting weight for keywords!
ListTagKeywords: No parameters width suffix: normalize by volume
ElmerAsciiMesh: Base mesh name: ./cylinder_in_cylinder
CylinderFit: Axis coordinate set to be: 1
ERROR:: LUDecomp: Matrix is singular.
ERROR:: InvertMatrix: inversion needs successfull LU-decomposition
STOP 1
```

Compared with the output of the same test on Ubuntu 24.04:
```
$ ../../src/ElmerSolver
ELMER SOLVER (v 9.0) STARTED AT: 2024/08/09 17:53:16
ParCommInit:  Initialize #PEs:            1
MAIN: 
MAIN: =============================================================
MAIN: ElmerSolver finite element software, Welcome!
MAIN: This program is free software licensed under (L)GPL
MAIN: Copyright 1st April 1995 - , CSC - IT Center for Science Ltd.
MAIN: Webpage http://www.csc.fi/elmer, Email elmeradm@csc.fi
MAIN: Version: 9.0 (Rev: 2766add03, Compiled: 2024-08-09)
MAIN:  Running one task without MPI parallelization.
MAIN:  Running with just one thread per task.
MAIN: =============================================================
MAIN: 
MAIN: 
MAIN: -------------------------------------
MAIN: Reading Model: case.sif
LoadInputFile: Scanning input file: case.sif
LoadInputFile: Scanning only size info
LoadInputFile: First time visiting
LoadInputFile: Reading base load of sif file
LoadInputFile: Loading input file: case.sif
LoadInputFile: Reading base load of sif file
CheckKeyword:  Unlisted keyword: [vtu: constraint modes analysis] in section: [simulation]
CheckKeyword:  Unlisted keyword: [increase element order] in section: [simulation]
CheckKeyword:  Unlisted keyword: [constraint modes matrix results] in section: [solver 1]
CheckKeyword:  Unlisted keyword: [expression 1] in section: [solver 2]
CheckKeyword:  Unlisted keyword: [expression 2] in section: [solver 2]
CheckKeyword:  Unlisted keyword: [follow cylinder boundary] in section: [boundary condition 1]
CheckKeyword:  Unlisted keyword: [follow cylinder boundary] in section: [boundary condition 2]
LoadInputFile: Number of BCs: 4
LoadInputFile: Number of Body Forces: 0
LoadInputFile: Number of Initial Conditions: 0
LoadInputFile: Number of Materials: 1
LoadInputFile: Number of Equations: 1
LoadInputFile: Number of Solvers: 2
LoadInputFile: Number of Bodies: 2
ListTagKeywords: Setting weight for keywords!
ListTagKeywords: No parameters width suffix: normalize by area
ListTagKeywords: Setting weight for keywords!
ListTagKeywords: No parameters width suffix: normalize by volume
ElmerAsciiMesh: Base mesh name: ./cylinder_in_cylinder
CylinderFit: Axis coordinate set to be: 3
CylinderFit: Axis coordinate set to be: 3
IncreaseElementOrder: Increasing element order from linear to quadratic!
ReleaseMeshFaceTables: Releasing number of faces: 674
IncreaseElementOrder: Elements increased to 2nd order serendipity elements
LoadMesh: Elapsed REAL time:     0.0051 (s)
MAIN: -------------------------------------
AddVtuOutputSolverHack: Adding ResultOutputSolver to write VTU output in file: case
StatElecSolver_init: Using Constraint Modes functionality for Capacitance Matrix
StatElecSolver_init: Suppressing bandwidth optimization in Capacitance Matrix computation!
OptimizeBandwidth: Initial bandwidth for electrostatics: 556
MAIN: Number of timesteps to be saved: 1
MAIN: 
MAIN: -------------------------------------
MAIN:  Steady state iteration:            1
MAIN: -------------------------------------
MAIN: 
StatElecSolver: ------------------------------------------------
StatElecSolver: Solving static electric field for insulators
StatElecSolverBulkAssembly: Elapsed REAL time:     0.0242 (s)
StatElecSolverBCAssembly: Elapsed REAL time:     0.0026 (s)
BiCGStabl:        5 0.8135E-10 0.8135E-10
ComputeChange: NS (ITER=1) (NRM,RELC): ( 0.62583759      2.0000000     ) :: electrostatics
StoreLumpedFluxes: Allocating lumped model of size: 1
FinalizeLumpedMatrix: Lumped Matrix
FinalizeLumpedMatrix:   1  1  1.001402000E+00
FinalizeLumpedMatrix: Constraint modes fluxes was saved to file CapacitanceMatrix.dat
FinalizeLumpedMatrix:  Normalization checksum:
FinalizeLumpedMatrix: Adding Constraint Modes Fluxes with "res:" to list
ComputeChange: SS (ITER=1) (NRM,RELC): ( 0.62583759      2.0000000     ) :: electrostatics
SaveScalars: -----------------------------------------
SaveScalars: Saving scalar values of various kinds
SaveScalars: Saving names of values to file: ./f.dat.names
SaveScalars: Saving values to file: ./f.dat
ComputeChange: SS (ITER=1) (NRM,RELC): (  1.0014020      0.0000000     ) :: savescalars
ComputeChange: SS (ITER=1) (NRM,RELC): (  1.0014020      2.0000000     ) :: savescalars
ResultOutputSolver: -------------------------------------
ResultOutputSolver: Saving with prefix: case
ResultOutputSolver: Creating list for saving - if not present
CreateListForSaving: Field Variables for Saving
ResultOutputSolver: Saving in unstructured VTK XML (.vtu) format
VtuOutputSolver: Saving results in VTK XML format with prefix: case
VtuOutputSolver: Saving number of partitions: 1
VtuOutputSolver: Saving each mode to different file
ResultOutputSolver: -------------------------------------
CompareToReferenceSolution: Solver 1 PASSED:  Norm = 6.25837594E-01  RefNorm = 6.25837594E-01
CompareToReferenceSolution: Relative Error to reference norm: 1.881983E-10
CompareToReferenceSolution: Solver 2 PASSED:  Norm = 1.00140200E+00  RefNorm = 1.00140200E+00
CompareToReferenceSolution: Relative Error to reference norm: 4.099167E-10
CompareToReferenceSolution: PASSED all 2 tests!
MAIN: *** Elmer Solver: ALL DONE ***
MAIN: The end
SOLVER TOTAL TIME(CPU,REAL):         0.13        0.60
ELMER SOLVER FINISHED AT: 2024/08/09 17:53:16
```

Notably, `CylinderFit: Axis coordinate set to be:` is `1` on Windows and `3` on Ubuntu.

When running with gdb to a breakpoint at [`MeshUtils.F90:14040`](https://github.com/ElmerCSC/elmerfem/blob/2766add0317ee0ccae8ef37e0559293ab8b44991/fem/src/MeshUtils.F90#L14040), I see the following on Ubuntu:
```
Thread 1 "ElmerSolver" hit Breakpoint 1, meshutils::cylinderfit (pmesh=0x5555557fdfc0, pparams=0x5555558f9df0, bcind=1, dim=3, fitparams=...)
    at .../elmerfem/fem/src/MeshUtils.F90:14040
14040	    AxisI = 1 
(gdb) p NiNj
$1 = (31.906038461164012, -1.4857677310686768e-09, 1.3877787807814457e-16, -1.4857677310686768e-09, 31.906038464428274, 5.5511151231257827e-17, 1.3877787807814457e-16, 5.5511151231257827e-17, 0.18792307440770833)
```
While I see the following on Windows:
```
Thread 1 hit Breakpoint 1, meshutils::cylinderfit (pmesh=0x7940a180, pparams=0x78fd5fc0, bcind=1, dim=<optimized out>, fitparams=...)
    at .../elmerfem/fem/src/MeshUtils.F90:14040
14040       AxisI = 1
(gdb) p NiNj
$1 = (0, 0, 0, 0, 0, 0, 0, 0, 0)
```

So, it looks like `NiNj` hasn't been set on Windows for some reason.

Do you have any hints how to look deeper into this issue?

### PR DESCRIPTION
**Pull request by mmuetzel**
MSMPI is set up such that some variables that should be shared between the MPI library and the program that is using it are dllimported via variables in common blocks. While that is likely working with DEC or Intel Fortran compilers on Windows, it doesn't work with GFortran.
See: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=47030

Afaict, that doesn't only affect MSMPI but all MPI implementations on Windows that are derived from MPICH (that also includes Intel MPI).

Add a test during configuration that checks whether the combination of Fortran compiler and MPI implementation supports the usage of `MPI_IN_PLACE`.
Define a preprocessor variable if it isn't supported.
Use a local buffer instead of `MPI_IN_PLACE` in that case.

If the combination of compiler and MPI implementation isn't affected by that issue, the changes in this PR should make no difference to the current behavior.

Fixes #521.

No additional tests are failing when applying these changes on top of #522.

### CODE REVIEW

**Comment by raback** [comment]
It seems that nix flake test failed here.

**Comment by mmuetzel** [comment]
Hmm... IIUC, the error is this:
```
elmer-ice> /build/source/elmerice/Solvers/CalvingRemeshMMG.F90:1412:20:
elmer-ice>  1412 |     buffer = FlowMax
elmer-ice>       |                    1
elmer-ice> Error: Syntax error in argument list at (1)
```

That's a bit baffling. I see the syntax error (and I'll push a fix shortly). But I wouldn't have expected that that line will be compiled on Linux.

For some reason the new feature test failed:
```
elmer> -- Checking whether MPI_IN_PLACE is supported with /nix/store/72bfhwxakf12r3gnizrmxxq29l97vkfl-gfortran-wrapper-13.3.0/bin/gfortran -- no
```

The test essentially tries to build and run the following code:
```
    PROGRAM TEST_MPI_IN_PLACE
      IMPLICIT NONE
      INTEGER :: ierr
      REAL(8) :: test1(3), test2(3)

      INCLUDE "mpif.h"

      test1(:) = 1
      test2 = test1
      PRINT *, "test1 =", test1

      CALL MPI_Init(ierr)
      CALL MPI_Allreduce(MPI_IN_PLACE, test1, 3, MPI_DOUBLE_PRECISION, MPI_SUM, MPI_COMM_WORLD)
      CALL MPI_Finalize(ierr)
      PRINT *, "test1 =", test1

      IF (.NOT.ALL(test1 == test2)) THEN
        STOP 1
      END IF

    END PROGRAM TEST_MPI_IN_PLACE
```

Could someone with access to NixOS please build that code with `mpif90` and attempt to run it? How does it fail?

**Comment by mk3z** [comment]
The output is

**Comment by mk3z** [comment]
The output is
```
 test1 =   1.0000000000000000        1.0000000000000000        1.0000000000000000
 test1 =   1.0000000000000000        1.0000000000000000        1.0000000000000000
```
for both `pkgs.mpi` and `pkgs.mpich`.

**Comment by mmuetzel** [comment]
Thank you for testing! 

Could you please also check the exit code after that program ran? In `bash` that would be `echo $?` after the program ran.

**Comment by mk3z** [comment]
Both exit with 0

**Comment by mmuetzel** [comment]
Thanks again.
That is looking good and what I would have expected. (I.e., the test succeeds and `MPI_IN_PLACE` is used like before.)

The configure test didn't actually build with `mpif90`. Instead, I tried to set the preprocessor and linker flags to mimick what `mpif90` would probably do different compared to `gfortran`. But maybe, something more would be needed to do that.
I pushed a change that tries to actually use `mpif90` in that test. Let's see if that makes a difference...

**Comment by mmuetzel** [comment]
That seems to have fixed the test result for the nix CI runner:
```
elmer> -- Checking whether MPI_IN_PLACE is supported with /nix/store/4hw0zym4ly57jflgvhq4f5mzhj5kwkff-openmpi-4.1.6-dev/bin/mpif90 -- yes
```
🎉

**Comment by raback** [comment]
Great work again! Testing of Elmer is on a new level. With the "ubuntu-parallel" testing on csc cloud this is very comprehensive.

**Pull request merged**
