### PR TITLE
Harmonize ElmerGrid, fix debug io

### PR DESCRIPTION
**Pull request by richb2k**
line length limitation, and add printf statements about using MATC when not compiled,

### CODE REVIEW

**Comment by richb2k** [comment]
Added date compiled to ElmerGUI console output, to be consistent with ElmerSolver and ElmerGrid.

**Comment by richb2k** [comment]
Add diagnostic output to the ElmerGUI solver log window, which is useful for parallel runs.  Rewrite the error message that is output when the MPI executable is not found.

**Comment by raback** [comment]
Hi Rich, Sorry for taking time. I had a look while doing something else and merged the fix. I had already done the harmonization part so I just picked the one changes file and will not use the PR to merge. Thanx for the fix!

**Comment by richb2k** [comment]
Hello Peter,  thanks for accepting the fix.  Rich.

**Pull request closed without merging**
