### PR TITLE
Add CMake module to find SPQR library and header. 

### PR DESCRIPTION
**Pull request by mmuetzel**
If building with CHOLMOD is enabled, the code also uses functions from the SPQR library.

Add a CMake module that looks for the SPQR library and header.
Look for SPQR package if `WITH_CHOLMOD` is enabled.
Link elmersolver library to CHOLMOD and SPQR in that case.

Also, enable building with CHOLMOD in the CI (where that is possible).

### CODE REVIEW

**Comment by raback** [comment]
This is interesting! SPQR seems to be able to utilize GPU's also. Is this routine used by Cholmod or also by Umfpack? So these need not be seperately interfaced? 

Recently the AMGx and ROCalution libraries have gotten interfaces but these are not much used yet even though the promise is great. I suppose SPQR would be a direct alternative to utilize NVidia GPU's to these.

**Comment by raback** [comment]
CoilSolver1 run with two processes seems to spoil the party on mingw. It takes >1500 s to compute... This is strange as no direct solvers are used here.

**Comment by juharu** [comment]
There is a separate interface routines to spqr, I was just being lazy at the time....
3.9.2024 0.27 "Peter R." kirjoitti:


This is interesting! SPQR seems to be able to utilize GPU's also. Is this routine used by Cholmod or also by Umfpack? So these need not be seperately interfaced? 

Recently the AMGx and ROCalution libraries have gotten interfaces but these are not much used yet even though the promise is great. I suppose SPQR would be a direct alternative to utilize NVidia GPU's to these.

**Comment by juharu** [comment]
We did test GPUs in this connection a while ago, admittedly only small scale (you surely have an email trace of this ...)
3.9.2024 0.27 "Peter R." kirjoitti:


This is interesting! SPQR seems to be able to utilize GPU's also. Is this routine used by Cholmod or also by Umfpack? So these need not be seperately interfaced? 

Recently the AMGx and ROCalution libraries have gotten interfaces but these are not much used yet even though the promise is great. I suppose SPQR would be a direct alternative to utilize NVidia GPU's to these.

**Comment by mmuetzel** [comment]
Hmm... The timeout on MinGW seems to be a regression from #549.
It already happened before: https://github.com/ElmerCSC/elmerfem/actions/runs/10672135068

That is strange. I'll try if I can reproduce the timeout locally...

**Comment by raback** [comment]
Oh yes, in Janurary this was SuiteSparse strategies were tested (with 4 CPUs) on some test case: cholmod 7 s, umfpack 40 s, spqr 120 s (cholmod is limited to symmetric pos.def. matrices).

**Comment by mmuetzel** [comment]
I can reproduce the timeout locally.
When I attach to the running `ElmerSolver_mpi` at that point, I can see that it is hanging in `sparitercomm::sparglobalnumbering`:
```
#0  0x00007fff4f3f00c4 in ntdll!ZwRemoveIoCompletion () from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x00007fff4ca98f43 in KERNELBASE!GetQueuedCompletionStatus () from C:\WINDOWS\System32\KernelBase.dll
#2  0x00007ffec8445abc in pmpi_type_create_f90_integer__ () from C:\WINDOWS\SYSTEM32\msmpi.dll
#3  0x00007ffec84305d5 in pmpi_type_create_f90_integer__ () from C:\WINDOWS\SYSTEM32\msmpi.dll
#4  0x00007ffec83d3e8e in msmpi!MPIR_Free () from C:\WINDOWS\SYSTEM32\msmpi.dll
#5  0x00007ffec8462bc1 in msmpi!PMPI_Recv () from C:\WINDOWS\SYSTEM32\msmpi.dll
#6  0x00007ffec84235bc in pmpi_recv__ () from C:\WINDOWS\SYSTEM32\msmpi.dll
#7  0x00007ffe883deec1 in sparitercomm::sparglobalnumbering (mesh=..., oldmesh=..., newnodecnt=2236, reorder=...) at D:/repo/elmerfem/fem/src/SParIterComm.F90:2343
#8  0x00007ffe884a1180 in parallelutils::parallelglobalnumbering (mesh=..., oldmesh=..., newnodes=2236, reorder=...) at D:/repo/elmerfem/fem/src/ParallelUtils.F90:1224
#9  0x00007ffe88290960 in splitmeshequal::updateparallelmesh (mesh=0x1ddec85cb20, newmesh=0x1ddec8b6c00) at D:/repo/elmerfem/fem/src/MeshUtils.F90:23425
#10 0x00007ffe882a966c in meshutils::splitmeshequal (mesh=0x1ddec85cb20, h=<error reading variable: Location address is not set.>) at D:/repo/elmerfem/fem/src/MeshUtils.F90:23066
#11 0x00007ffe87f3955c in modeldescription::loadmodel (modelname=..., boundariesonly=.FALSE., numprocs=2, mype=1, meshindex=0, _modelname=128) at D:/repo/elmerfem/fem/src/ModelDescription.F90:2925
#12 0x00007ffe886a9cbd in elmersolver (initialize=0) at D:/repo/elmerfem/fem/src/ElmerSolver.F90:390
#13 0x00007ff7969a1698 in solver () at D:/repo/elmerfem/fem/src/Solver.F90:57
```

In case that is helpful, the values of some parameters at that point:
```
(gdb) thread 1
[Switching to thread 1 (Thread 11004.0x69a4)]
#0  0x00007fff4f3f00c4 in ntdll!ZwRemoveIoCompletion () from C:\WINDOWS\SYSTEM32\ntdll.dll
(gdb) bt
#0  0x00007fff4f3f00c4 in ntdll!ZwRemoveIoCompletion () from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x00007fff4ca98f43 in KERNELBASE!GetQueuedCompletionStatus () from C:\WINDOWS\System32\KernelBase.dll
#2  0x00007ffec8445abc in pmpi_type_create_f90_integer__ () from C:\WINDOWS\SYSTEM32\msmpi.dll
#3  0x00007ffec84305d5 in pmpi_type_create_f90_integer__ () from C:\WINDOWS\SYSTEM32\msmpi.dll
#4  0x00007ffec83d3e8e in msmpi!MPIR_Free () from C:\WINDOWS\SYSTEM32\msmpi.dll
#5  0x00007ffec8462bc1 in msmpi!PMPI_Recv () from C:\WINDOWS\SYSTEM32\msmpi.dll
#6  0x00007ffec84235bc in pmpi_recv__ () from C:\WINDOWS\SYSTEM32\msmpi.dll
#7  0x00007ffe883deec1 in sparitercomm::sparglobalnumbering (mesh=..., oldmesh=..., newnodecnt=2236, reorder=...)
    at D:/repo/elmerfem/fem/src/SParIterComm.F90:2343
#8  0x00007ffe884a1180 in parallelutils::parallelglobalnumbering (mesh=..., oldmesh=..., newnodes=2236, reorder=...)
    at D:/repo/elmerfem/fem/src/ParallelUtils.F90:1224
#9  0x00007ffe88290960 in splitmeshequal::updateparallelmesh (mesh=0x1ddec85cb20, newmesh=0x1ddec8b6c00)
    at D:/repo/elmerfem/fem/src/MeshUtils.F90:23425
#10 0x00007ffe882a966c in meshutils::splitmeshequal (mesh=0x1ddec85cb20, h=<error reading variable: Location address is not set.>)
    at D:/repo/elmerfem/fem/src/MeshUtils.F90:23066
#11 0x00007ffe87f3955c in modeldescription::loadmodel (modelname=..., boundariesonly=.FALSE., numprocs=2, mype=1, meshindex=0, _modelname=128)
    at D:/repo/elmerfem/fem/src/ModelDescription.F90:2925
#12 0x00007ffe886a9cbd in elmersolver (initialize=0) at D:/repo/elmerfem/fem/src/ElmerSolver.F90:390
#13 0x00007ff7969a1698 in solver () at D:/repo/elmerfem/fem/src/Solver.F90:57
(gdb) up 7
#7  0x00007ffe883deec1 in sparitercomm::sparglobalnumbering (mesh=..., oldmesh=..., newnodecnt=2236, reorder=...)
    at D:/repo/elmerfem/fem/src/SParIterComm.F90:2343
2343            CALL MPI_RECV( DataSize, 1, MPI_INTEGER, i-1, 900, ELMER_COMM_WORLD, status, ierr )
(gdb) p DataSize
$1 = 189
(gdb) p i
$2 = 1
(gdb) p status
$3 = (4, 0, 0, 100, 12064)
(gdb)
```

I made the following change to that file in #549:
``` diff
diff --git a/fem/src/SParIterComm.F90 b/fem/src/SParIterComm.F90
index 13ddbb27fa..d12a565ab3 100644
--- a/fem/src/SParIterComm.F90
+++ b/fem/src/SParIterComm.F90
@@ -508,8 +508,8 @@ SUBROUTINE FindActivePEs( ParallelInfo, SourceMatrix, JustNeighbours )
           buf(j) = ptr % e2
           ptr => ptr % next
         END DO
-        CALL MPI_BSEND(j,1,MPI_INTEGER,i-1, 20000,ELMER_COMM_WORLD,status,ierr)
-        IF (j>0) CALL MPI_BSEND(buf,j,MPI_INTEGER,i-1,20001,ELMER_COMM_WORLD,status,ierr)
+        CALL MPI_BSEND(j,1,MPI_INTEGER,i-1, 20000,ELMER_COMM_WORLD,ierr)
+        IF (j>0) CALL MPI_BSEND(buf,j,MPI_INTEGER,i-1,20001,ELMER_COMM_WORLD,ierr)
       END DO
 
       DO i=1,ParEnv % PEs
@@ -2489,7 +2489,7 @@ SUBROUTINE SParGlobalNumbering( Mesh, OldMesh, NewNodeCnt, Reorder )
      Iterate = Iterate+1
      IF(Iterate > MaxIterates ) THEN
         WRITE(*,'(A,I6,A)') 'SParIterGlobalNumbering: PE: ', ParEnv % MyPE+1,'Max iterations exceeded'
-        CALL MPI_FINALIZE( ELMER_COMM_WORLD, ierr )
+        CALL MPI_FINALIZE( ierr )
      END IF
      DO i = n, Mesh % NumberOfNodes
         Mesh % ParallelInfo % GlobalDOFs(i) = 0
```

That was to fix compiler errors when using the MPI module. According to the upstream documentation of MPI, those changes look fine though...

I wonder if that could be related. (Maybe, different stack layout now?)

It could also be that I messed up when updating the `MPI` module for upstream MSYS2: https://github.com/msys2/MINGW-packages/pull/21797

In particular, `TYPE(:)` is a Fortran 2008 feature if I understand correctly. I thought using it in the MPI module interface definition was working in initial tests. But maybe there are more subtle issues when trying to use a Fortran 2008 module from Fortran 90 code?

For the moment, I'd guess that this is an issue in the upstream MPI module in MSYS2.

I'll try to look some more into that when I come around to it...

**Comment by juharu** [comment]
Thanks Markus!

**Comment by mmuetzel** [comment]
I opened a PR for upstream MSYS2 that should fix that error:
https://github.com/msys2/MINGW-packages/pull/21840

(At least, I can no longer reproduce the issue locally with that change.)

**Pull request merged**
