### PR TITLE
GUI icons update

### PR DESCRIPTION
**Pull request by t7saeki**
This PR is to replace Oxygen icons with Tango-based icons. New icons were made by using icons in Tango icon theme. Some icons were just taken from Tango icon theme and others were generated by combining some icons in Tango icon theme. Tango icon theme is in the public domain. So, there is no license issue like new version of Oxygen icons. 
Some of previous icons were too tiny to see in certain display settings. The new icons have multiple sizes (22x22, 32x32 and 48x48 for now) so as to solve such a problem.

### CODE REVIEW

**Comment by richb2k** [comment]
Would it be practical to add to the about-box the compilation date?  Similar to how Elmersolver includes a compiled date in every solver log?

**Comment by t7saeki** [comment]
That's a great idea! I have added the completion date to the end.

**Comment by richb2k** [comment]
Thanks for adding the compiled on date.  One other small item, it would be proper to change the spelling of Peter's last name to match as shown in the manuals, such as on the title page of the ElmerSolver Manual.

**Comment by richb2k** [comment]
I tried compiling the tango branch, and received this error:
C:\msys64\mingw64\bin\windres.exe: can't open icon file `icons/Mesh3D.ico': No such file or directory
Not sure if this is due to compiling on Windows 10, or maybe something else is going on?
Copying Mesh3D.ico into the tango branch allowed compiling to complete.  The about box now includes the date compiled.

**Comment by t7saeki** [comment]
Good catch! As for spelling, I noticed that other source files I had edited also had same issue in header comment. I guess this is a problem in character code settings in my editor or something.
As for Mesh3D.ico. I misunderstood this was not used any more and deleted it, but didn't noticed when I compiled (maybe due to cmake cache)  

I have corrected the spelling and restored Mesh3D.ico, and confirmed compilation after deleting cache. Hope this works.

**Comment by richb2k** [comment]
Hello again, great, it compiled fine for me on Windows 10.  Thanks for the spelling correction, it's a nice detail.  Looks good to me!

**Comment by t7saeki** [comment]
Thank you too for your reporting details on related issues as always. Very helpful for me!

**Comment by richb2k** [comment]
Well, how about a slightly unrelated issue?  I've never seen the 'Whatis' feature in the EDF xml files work.  There is a lot of good information in the EDF xml files in the 'Whatis' field, but it never shows up.

**Comment by t7saeki** [comment]
It shows up by moving the focus to the relevant widget and press SHIFT+F1. This is a standard behavior of Qt widgets.

**Comment by richb2k** [comment]
Amazing!  After using ElmerGUI for many years, that's the first time I noticed anything about how to get Whatis to work.  Now that you mentioned it, I searched the ElmerGUI manual for 'F1' and the use of Shift F1 is nicely described.  As they say, Read The Manual.
Would it be possible to add another Whatis input combination?  Such as double left mouse button click or maybe single right mouse button click?  This might be more intuitive for Windows users.  Take gmsh for example, double left mouse button click while in the graphics window will open a menu.
Further, perhaps adding another entry to the Help menu, such as 'Context Help' and explain how to open the Whatis tool tip?  Another Help menu entry such as 'Get Started', where links to the docs and the forum are presented?  If you can add the menu entries, I can help with editing the content.  Thanks, Rich.

**Comment by raback** [comment]
Great work again Saeki! These icons seem very economical also. And thanx Rich for testing it also. I also compiled it without issues and tested it quickly, so I think it is safe to merge. Have a Great New Year!

**Comment by t7saeki** [comment]
Thanks! I will prepare another PR for Rich's proposal on Context Help, etc.

**Pull request merged**
